// Code generated by protoc-gen-go from "data.proto"
// DO NOT EDIT!

package test

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type Skill int32

const (
    Skill_ASM    Skill = 0
    Skill_C      Skill = 1
    Skill_Cpp    Skill = 2
    Skill_Java   Skill = 3
    Skill_Python Skill = 4
    Skill_Perl   Skill = 5
)

var Skill_name = map[int32]string{
    0:  "ASM",
    1:  "C",
    2:  "Cpp",
    3:  "Java",
    4:  "Python",
    5:  "Perl",
}
var Skill_value = map[string]int32{
    "ASM":    0,
    "C":      1,
    "Cpp":    2,
    "Java":   3,
    "Python": 4,
    "Perl":   5,
}

func NewSkill(x Skill) *Skill {
    e := Skill(x)
    return &e
}
func (x Skill) String() string {
    return proto.EnumName(Skill_name, int32(x))
}

type Member struct {
    Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
    Age              *int32  `protobuf:"varint,2,req,name=age" json:"age,omitempty"`
    Skills           []Skill `protobuf:"varint,3,rep,packed,name=skills,enum=test.Skill" json:"skills,omitempty"`
    Email            *string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
    XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Member) Reset()         { *this = Member{} }
func (this *Member) String() string { return proto.CompactTextString(this) }

type Club struct {
    Name             *string   `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
    Member           []*Member `protobuf:"bytes,2,rep,name=member" json:"member,omitempty"`
    XXX_unrecognized []byte    `json:",omitempty"`
}

func (this *Club) Reset()         { *this = Club{} }
func (this *Club) String() string { return proto.CompactTextString(this) }

type Reply struct {
    Average          *float64 `protobuf:"fixed64,1,req,name=average" json:"average,omitempty"`
    XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *Reply) Reset()         { *this = Reply{} }
func (this *Reply) String() string { return proto.CompactTextString(this) }

func init() {
    proto.RegisterEnum("test.Skill", Skill_name, Skill_value)
}
